# Generated by Django 5.2.5 on 2025-10-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0002_remove_fechasdisponibles_nombre_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechasdisponibles',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
