# Generated by Django 5.2.6 on 2025-10-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0004_publi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publi',
            name='fexha',
        ),
    ]
