# Generated by Django 5.2.6 on 2025-10-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0005_remove_publi_fexha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publi',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
