# Generated by Django 5.2.6 on 2025-11-07 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0006_alter_publi_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('adulto_mayor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_realizados', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_recibidos', to=settings.AUTH_USER_MODEL)),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funciones.fechasdisponibles')),
            ],
            options={
                'unique_together': {('estudiante', 'adulto_mayor')},
            },
        ),
    ]
