# Generated by Django 5.2.5 on 2025-11-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0007_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechasdisponibles',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
