# Generated by Django 5.2.5 on 2025-11-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0008_fechasdisponibles_disponible'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together=set(),
        ),
    ]
