# Generated by Django 5.2.6 on 2025-10-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comuna_usuarios_comuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='usuarios',
            name='areas',
            field=models.ManyToManyField(blank=True, to='app.area'),
        ),
    ]
