# Generated by Django 5.2.7 on 2025-11-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_area_usuarios_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='campus',
            field=models.CharField(choices=[('SANJO', 'Campus San Joaquin'), ('VITA', 'Campus Vitacura')], default='SANJO', max_length=20),
        ),
    ]
