# Generated by Django 5.2.7 on 2025-11-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuarios_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='campus',
            field=models.CharField(choices=[('SANJO', 'Campus San Joaquin'), ('VITA', 'Campus Vitacura')], max_length=20),
        ),
    ]
